### ISSUE TITLE
Canni deletes messages

### ISSUE THREAD

**Issue by flynnmlp** [steffansk1997/CanniBot#32]
As it is, Canni will delete any message that starts with "boop", even though the message might contain more information.
Messages should not be deleted unless they consist of nothing more than a command.

**Comment by ChrisFhey** [comment]
Hey Flynn,

Thanks for your feedback.
I've forwarded your concerns to Merte. They'll be looking at this issue when they can.

**Comment by tomtenberge** [comment]
i will be working on it as soon as i can!

**Comment by ChrisFhey** [comment]
This issue should be fixed in the current Canni version

**Comment by flynnmlp** [comment]
I can't reopen this bug, but the same also applies for hugs. (I believe this wasn't the case yet when I reported the bug.)

**Comment by ChrisFhey** [comment]
I've reopened it for you.

I noticed it as well. I'll fix it tomorrow.

**Comment by ChrisFhey** [comment]
Fixed and merged to master. It'll be included the next time Canni is updated.
